services:
  tg_bot:
    build: 
      context: .
    env_file:
      - .env
    depends_on:
      - postgres_bot_db

# Database with init.sql file to create first table with service name postgres_bot_db 
  postgres_bot_db:
    container_name: db_bot_telegram
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./init_DB:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5423:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

# Pgadmin for database in bot

pgadmin:
  container_name: pgadmin_db_bot
  image: dpage/pgadmin4:latest
  env_file:
    - .env
  volumes:
    - ./pgadmin:/var/lib/pgadmin
  ports:
    - "${PGADMIN_PORT_HOST}:80"
  restart: unless-stopped

