services:
  postgres_bot_db:
    container_name: db_bot_telegram
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./init_DB:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5423:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telegram_bot_tester -d bot_db"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped